# Generated by Django 3.1.6 on 2022-08-05 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Aventure', 'Aventure'), ('Fantastique', 'Fantastique'), ('Thriller', 'Thriller'), ('Romance', 'Romance'), ('Horreur', 'Horreur'), ('Science-fiction', 'Science-fiction')], max_length=50),
        ),
    ]
