# Generated by Django 3.1.6 on 2022-08-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20220805_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='wikipedia',
            field=models.URLField(blank=True, default='NULL'),
        ),
    ]
